<?php

/*********************************************
*
* Module de paiement
* Crédit Mutuel
* Abtel
* 
*********************************************/

require_once( dirname(dirname(__FILE__)).'/TypePaiement.interface.php' );

class ReservationsTypePaiementPayBox extends Plugin implements ReservationsTypePaiementPlugin {

	/**
	* initStatePaiement
	* Initiliase le paiement avec ses propriétés particulières
	*/
	public function initStatePaiement() {
		return 0;
	}


	public function __construct() {
		if (!defined("PAYBOX_LIB_DIR"))define("PAYBOX_LIB_DIR", dirname(__FILE__));
	}

	/**
	 * getCodeHTML
	 * return the html code generated by the payment module.
	 * $paiement = Reservations/Paiement Objectclass
	 **/
	public function getCodeHTML( $paiement ) {
	    $facture = $paiement->getOneParent('Facture');
		// Params
		//mode d'appel
		     //$PBX_MODE        = '4';    //pour lancement paiement par exécution
		     //$PBX_MODE        = '1';    //pour lancement paiement par URL
		//identification
		     $PBX_SITE        = $this->Params['IDSITE'];
		     $PBX_RANG        = $this->Params['RANG'];
		     $PBX_IDENTIFIANT = $this->Params['IDENTIFIANT'];
		//gestion de la page de connection : paramétrage "invisible"
		     $PBX_WAIT        = '0';
		     $PBX_TXT         = " ";
		     $PBX_BOUTPI      = "nul";
		     $PBX_BKGD        = "white";
		     $PBX_HASH        = "SHA512";
		//informations paiement (appel)
		     $PBX_TOTAL       = round($paiement->Montant * 100);
		     $PBX_DEVISE      = '978';
		     $PBX_CMD         = sprintf("%06d", $paiement->Id);
		     $PBX_PORTEUR     = "ledomedufoot@bbox.fr";//$GLOBALS["Systeme"]->Conf->get("GENERAL::INFO::ADMIN_MAIL");
             $PBX_TYPEPAIEMENT= 'CARTE';
             $PBX_TYPECARTE   = 'CB';
		//informations nécessaires aux traitements (réponse)
		     //$PBX_RETOUR      = "auto:A;amount:M;ident:R;trans:T";
		     $PBX_RETOUR      = "Mt:M;Ref:R;Auto:A;Erreur:E";
		     $PBX_EFFECTUE    = "http://".$_SERVER['HTTP_HOST']."/".Sys::getMenu('Reservations/Facture/'.$facture->NumFac.'/Confirmation');
		     $PBX_REFUSE      = "http://".$_SERVER['HTTP_HOST']."/".Sys::getMenu('Reservations/Facture/'.$facture->NumFac.'/Annulation');
		     $PBX_ANNULE      = "http://".$_SERVER['HTTP_HOST']."/".Sys::getMenu('Reservations/Facture/'.$facture->NumFac.'/Annulation');
		     $PBX_REPONDRE_A  = "http://".$_SERVER['HTTP_HOST']."/".Sys::getMenu('Reservations/Facture/'.$facture->NumFac.'/IPN');
		//page en cas d'erreur
		     $PBX_ERREUR      = "http://".$_SERVER['HTTP_HOST']."/".Sys::getMenu('Reservations/Facture/'.$facture->NumFac.'/Annulation');
		//date
		     $PBX_TIME	      =  date("c");
		//paiement différé
             $PBX_DIFF        = "90";
		
		//construction de la chaîne de paramètres
             $PBX= "PBX_SITE=$PBX_SITE&PBX_RANG=$PBX_RANG&PBX_IDENTIFIANT=$PBX_IDENTIFIANT&PBX_TOTAL=$PBX_TOTAL&PBX_DEVISE=$PBX_DEVISE&PBX_CMD=$PBX_CMD&PBX_PORTEUR=$PBX_PORTEUR&PBX_RETOUR=$PBX_RETOUR&PBX_HASH=$PBX_HASH&PBX_TIME=$PBX_TIME&PBX_DIFF=$PBX_DIFF";

		// Si la clé est en ASCII, On la transforme en binaire
		$binKey = pack("H*", $this->Params['KEY']);
	
		//on génère la clef HMAC
		$hmac = strtoupper(hash_hmac('sha512', $PBX, $binKey));
		
		//on renvoie le formulaire
		return '
		<form method="POST" id="payment-'.$PBX_CMD.'" action="https://preprod-tpeweb.e-transactions.fr/cgi/MYchoix_pagepaiement.cgi">
			<input type="hidden" name="PBX_SITE" value="'.$PBX_SITE.'">
			<input type="hidden" name="PBX_RANG" value="'.$PBX_RANG.'">
			<input type="hidden" name="PBX_IDENTIFIANT" value="'.$PBX_IDENTIFIANT.'">
			<input type="hidden" name="PBX_TOTAL" value="'.$PBX_TOTAL.'">
			<input type="hidden" name="PBX_DEVISE" value="'.$PBX_DEVISE.'">
			<input type="hidden" name="PBX_CMD" value="'.$PBX_CMD.'">
			<input type="hidden" name="PBX_PORTEUR" value="'.$PBX_PORTEUR.'">
<!--			<input type="hidden" name="PBX_TYPEPAIEMENT" value="'.$PBX_TYPEPAIEMENT.'">
			<input type="hidden" name="PBX_TYPECARTE" value="'.$PBX_TYPECARTE.'">-->
			<input type="hidden" name="PBX_RETOUR" value="'.$PBX_RETOUR.'">
<!--			<input type="hidden" name="PBX_EFFECTUE" value="'.$PBX_EFFECTUE.'">
			<input type="hidden" name="PBX_REFUSE" value="'.$PBX_REFUSE.'">
			<input type="hidden" name="PBX_ANNULE" value="'.$PBX_ANNULE.'">
			<input type="hidden" name="PBX_REPONDRE_A" value="'.$PBX_REPONDRE_A.'">-->
			<input type="hidden" name="PBX_HASH" value="'.$PBX_HASH.'">
			<input type="hidden" name="PBX_TIME" value="'.$PBX_TIME.'">
			<input type="hidden" name="PBX_DIFF" value="'.$PBX_DIFF.'">
			<input type="hidden" name="PBX_HMAC" value="'.$hmac.'">
			<input type="submit" value="Envoyer">
		</form>
		<script>
            (function () {
                $("#payment-'.$PBX_CMD.'").submit();
            })();		
        </script>
		';
	}

	public function serveurAutoResponse( $paiement, $commande ) {
		// Vérification signature
		$signature = sha1(
			$_POST['version'] . "+" . $_POST['site_id'] . "+" . $_POST['ctx_mode'] . "+" . $_POST['trans_id'] . "+" . $_POST['trans_date'] . "+" . 
			$_POST['validation_mode'] . "+" . $_POST['capture_delay'] . "+" . $_POST['payment_config'] . "+" . $_POST['card_brand'] ."+" . 
			$_POST['card_number'] . "+" . $_POST['amount'] . "+" . $_POST['currency'] ."+" . $_POST['auth_mode'] ."+" . $_POST['auth_result'] ."+" .
			$_POST['auth_number'] ."+" . $_POST['warranty_result'] ."+" . $_POST['payment_certificate'] ."+" . $_POST['result'] ."+" . $_POST['hash'] . "+" . $this->Params["CERTIFICAT"]
		);
		if($signature != $_POST['signature']) {
			return false;
		}

		// Retourne le code d'état du paiement
		$etat = ($_POST['result'] == '00') ? 1 : 2;
		return array(
			'etat' => $etat,
			'ref' => $_POST['auth_number']
		);
	}

	public function retrouvePaiementEtape4s() {
		if(isset($_GET['Ref']) and !empty($_GET['Ref'])) return round($_GET['Ref']);
		return false;
	}

	public function affichageEtape5( $paiement, $commande ) {
		if($commande->Paye) return 'Votre commande a été enregistrée sous le numéro '. $commande->RefCommande;
		else return 'Une erreur est survenue lors du paiement de la commande '. $commande->RefCommande . '<br /> Vous pouvez contacter le support via ce <a href="/Contact">formulaire</a> en rappelant cette référence.';
	}

}