#!/bin/bash
#***********************************#
#	PARTIE CONFIGURABLE	#
#***********************************#

# Identification de la base
USER='root'
PASSWORD='zH34Y6u5'

# Definition du repertoire racine
# ex : /mon/repertoire/export/sql
ROOT_DIRECTORY='/home/sauvegarde/sql/jour'

# Localisation de l outil mysqldump
# ex : /usr/bin/mysqldump
PATH_MYSQLDUMP='/usr/bin/mysqldump'

# Definition du repertoire log
# ex : /le/repertoire/content/mes/logs
LOG_PREFIX_DIRECTORY='/home/sauvegarde/sql/logs'

# Definition du nom de fichier contenant les logs
# ex : dump_databases.log
LOG_FILENAME='mysql_jour.log'

# Persistance des sauvegardes en nombres de jours
# ex : 30
MTIME=1

# Persistance des sauvegardes en secondes
# 7 jours
STIME=36000

# Persistance des sauvegarde en minutes
# 40 rotations de 5 minutes soit 200 mins
MINTIME=+1440

# Calcul de la date de comparaison
SDATE_COMPARE=`date +'%Y%m%d%H%M%S'`

# Variable code retour
# ex : OK=0
# ex : ERR=3
OK=0
ERR=3

# Format de l horodatage des fichiers SQL
# ex : %Y%m%d_%H%M%S
# a pour horodatage le fichier sql : mabase_20110614_222509.sql
#FORMAT_DATE='%Y%m%d_%H%M%S'
FORMAT_DATE='%Y%m%d'

#**********************************************#
#	FIN DE LA PARTIE CONFIGURABLE	#
#**********************************************#

#########################################
# CONFIGURATION GLOBALE
#########################################

# Variable globale concernant le repertoire cible des dumps
TARGET_PATH=${ROOT_DIRECTORY}

# Variable globale concernant les LOGS
LOG_DIRECTORY=${LOG_PREFIX_DIRECTORY}
LOG_PATH=${LOG_DIRECTORY}/${LOG_FILENAME}

# Recuperation du datetime courant
CUR_DATE=`date +$FORMAT_DATE`

#########################################

#########################################
# 	FONCTIONS
#########################################

# Fonction redirectLog v_message [v_type]
# v_message 			: Message a afficher / sauvegarder
# v_type (optionnel) 	: Type de message a traiter
#		0 : Afficher le message sur STDOUT et envoyer le message dans le fichier de LOG (mode par defaut)
#		1 : Afficher uniquement le message sur STDOUT
#		2 : Afficher uniquement le message dans le fichier de LOG
function redirectLog {
	########################
	# Variables globales de la fonction    #
	########################

	# Definition des codes retours de la fonction
	E_PARAM_ERR=250
	E_OK=0

	# Definition du VTYPE par defaut
	DEFAULT_VTYPE=0

	#############################
	# Traitement des parametres de la fonction   #
	#############################

	# Si le parametre obligatoire v_message n est pas present
	if [ -z "$1" ]
	then
		# Sortie du programme
		echo "[ERR] Erreur lors de l appel de la fonction redirectLog"
		exit $E_PARAM_ERR
	fi

	# Recuperation du parametre obligatoire v_message
	VMESSAGE=$1

	# Test si presence du parametre v_type (optionnel)
	if [ -z "$2" ]
	then
		# Application du VTYPE par defaut
		VTYPE=$DEFAULT_VTYPE
	else
		# Recuperation du parametre v_type
		VTYPE=$2
	fi

	##############################
	# Traitement suivant le type de sortie   VTYPE #
	##############################

	# Suivant le type de sortie definie par l argument VTYPE
	case $VTYPE in
	0)
		# Affichage sur STDOUT + LOG
		echo "$VMESSAGE"
		echo "$VMESSAGE" >> ${LOG_PATH}
	;;
	1)
		# Affichage uniquement sur STDOUT
		echo "$VMESSAGE"
	;;
	2)
		# Affichage uniquement dans la LOG
		echo "$VMESSAGE" >> ${LOG_PATH}
	;;
	esac
}
#########################################

#########################################
# TEST ARBORESCENCE / BINAIRES
#########################################

# Test presence du TARGET_PATH
if [ ! -d $TARGET_PATH ]
then
	redirectLog "Le repertoire $ROOT_DIRECTORY n est pas present" 1
	redirectLog "[CODE_RETOUR] $ERR" 1
	exit $ERR
fi

# Test presence du LOG_DIRECTORY
if [ ! -d $LOG_DIRECTORY ]
then
	redirectLog "Le repertoire $LOG_DIRECTORY n est pas present" 1
	redirectLog "[CODE_RETOUR] $ERR" 1
	exit $ERR
fi

# Test presence du LOG_DIRECTORY
if [ ! -f $PATH_MYSQLDUMP ]
then
	redirectLog "Le binaire $PATH_MYSQLDUMP n est pas present" 1
	redirectLog "sudo apt-get install mysql-server ?" 1
	redirectLog "[CODE_RETOUR] $ERR" 1
	exit $ERR
fi

#########################################
# Initialisation du fichier de LOG
redirectLog "####################################"
redirectLog "#### BACKUP BDD $CUR_DATE ####"

#########################################

# Exportation des bases de donnees
# Suppression des sauvegardes datant de plus de ${MTIME} jours
# find ${TARGET_PATH} -name "*.sql" -mtime ${MTIME} -delete

# Suppression des sauvegardes datant de plus de ${STIME} secondes
# creation du fichier de comparaison pour find
#touch -t ${SDATE_COMPARE} ${TARGET_PATH}/find_compare.txt

# Suppression des sauvegarde datant de plus de ${MINTIME} minutes
find ${TARGET_PATH} -name "*.sql" -mmin ${MINTIME} -delete

# Pour chaque produit specifie en variable globale
BASES="$(mysql -u ${USER} -h sql1.eng.systems -p${PASSWORD} -Bse 'show databases')"
for PRODUCT in $BASES
do
	# Info LOG
	redirectLog "[INFO] Tentative d export de la base '$PRODUCT' vers '${TARGET_PATH}/${PRODUCT}_${CUR_DATE}.sql'"

	# Dump de la base specifie suivant le produit et sa version
	"$PATH_MYSQLDUMP" -u "${USER}" -h sql1.eng.systems -p"${PASSWORD}" ${PRODUCT} > ${TARGET_PATH}/${PRODUCT}_${CUR_DATE}.sql 2>> ${LOG_PATH}

	# Test du code retour
	if [ $? -ne 0 ]
	then
                if [ $PRODUCT != information_schema ]
                then
                        echo "Une table doit être endommagée dans la base '$PRODUCT' sur SQL1.ENG.SYSTEMS" | /bin/mail -s "ERREUR BACKUP BASE '$PRODUCT' SUR SQL1.ENG.SYSTEMS" enguer@enguer.com
                        redirectLog "[ERR] Echec de l export de la base '$PRODUCT'"
			redirectLog "[CODE_RETOUR] $ERR"
			redirectLog "####################################"
			redirectLog "LOG : $LOG_PATH" 1
                fi
		#exit $ERR
	else
		redirectLog "[INFO] Export de la base '$PRODUCT' [OK]"
	fi
done

# Cloture du fichier LOG
redirectLog "[CODE_RETOUR] $OK"
redirectLog "####################################"

# Code retour OK
exit $OK
