#!/bin/bash
php cron.php admin.ecluse.local Boutique/Categorie/1026/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1025/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1024/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1023/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1022/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1021/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1020/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1019/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1018/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1017/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1016/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1015/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1014/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1013/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1012/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1011/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1010/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1009/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1008/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1007/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1006/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1005/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1004/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1003/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1002/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1001/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/1000/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/999/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/998/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/997/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/996/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/995/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/994/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/993/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/992/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/991/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/990/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/989/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/988/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/987/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/986/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/985/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/984/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/983/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/982/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/981/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/980/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/979/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/978/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/977/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/976/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/975/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/974/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/973/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/972/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/971/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/970/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/969/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/968/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/967/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/966/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/965/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/964/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/963/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/962/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/961/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/960/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/959/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/958/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/957/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/956/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/955/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/954/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/953/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/952/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/951/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/950/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/949/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/948/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/947/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/946/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/945/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/944/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/943/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/942/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/941/ParserProduit.cron
