#!/bin/bash
php cron.php admin.ecluse.local Boutique/Categorie/940/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/939/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/938/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/937/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/936/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/935/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/934/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/933/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/932/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/931/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/930/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/929/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/928/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/927/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/926/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/925/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/924/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/923/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/922/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/921/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/920/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/919/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/918/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/917/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/916/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/915/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/914/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/913/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/912/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/911/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/910/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/909/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/908/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/907/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/906/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/905/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/904/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/903/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/902/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/901/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/900/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/899/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/898/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/897/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/896/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/895/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/894/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/893/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/892/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/891/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/890/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/889/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/888/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/887/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/886/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/885/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/884/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/883/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/882/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/881/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/880/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/879/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/878/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/877/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/876/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/875/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/874/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/873/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/872/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/871/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/870/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/869/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/868/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/867/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/866/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/865/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/864/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/863/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/862/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/861/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/860/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/859/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/858/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/857/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/856/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/855/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/854/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/853/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/852/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/851/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/850/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/849/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/848/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/847/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/846/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/845/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/844/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/843/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/842/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/841/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/840/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/839/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/838/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/837/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/836/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/835/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/834/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/833/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/832/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/831/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/830/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/829/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/828/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/827/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/826/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/825/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/824/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/823/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/822/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/821/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/820/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/819/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/818/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/817/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/816/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/815/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/814/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/813/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/812/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/811/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/810/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/809/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/808/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/807/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/806/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/805/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/804/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/803/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/802/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/801/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/800/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/799/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/798/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/797/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/796/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/795/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/794/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/793/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/792/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/791/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/790/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/789/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/788/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/787/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/786/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/785/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/784/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/783/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/782/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/781/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/780/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/779/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/778/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/777/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/776/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/775/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/774/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/773/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/772/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/771/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/770/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/769/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/768/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/767/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/766/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/765/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/764/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/763/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/762/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/761/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/760/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/759/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/758/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/757/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/756/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/755/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/754/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/753/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/752/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/751/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/750/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/749/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/748/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/747/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/746/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/745/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/744/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/743/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/742/ParserProduit.cron
php cron.php admin.ecluse.local Boutique/Categorie/741/ParserProduit.cron
[0;32m
Closing connections ...[0m
[0;32m------------------------------------[0m
