(`Id`,`tmsCreate`,`userCreate`,`tmsEdit`,`userEdit`,`uid`,`gid`,`umod`,`gmod`,`omod`,`Titre`,`Icone`,`Ordre`,`Image`,`Texte`) VALUES ("24","1346849270","1","1383842317","103","1","0","7","7","7","Direct Drive","Home/103/Products/Technologie/Picto_direct_drive_1.png","6","Home/101/Products/Technologie/advert_HRD_Rail_IKSURFMAG_online_1470X995_EN_VF_0.jpg","The Direct Drive technology is present on our boards since 2001, and refers to a board with minimal thickness, a 100% wood core and a 100% fiberglass envelope. These interlocking elements meet the F-ONE standards for a kite board and provide maximum durability.
The Direct Drive translate into a precise board, quick and active as it erases the flaws of the water surface, collecting its energy and giving it back for the best performance. The feeling of riding a rock solid board always in contact with the water without suffering from it is even greater.")
(`Id`,`tmsCreate`,`userCreate`,`tmsEdit`,`userEdit`,`uid`,`gid`,`umod`,`gmod`,`omod`,`Titre`,`Icone`,`Ordre`,`Image`,`Texte`) VALUES ("28","1346853192","1","1383842238","103","1","0","7","7","7","Dynamic Flex","Home/103/Products/Technologie/Picto_dynamic_flex_0.png","4","","Flexibility and impact absorption are synonymous with comfort; however comfort does not mean sacrificing control and performance. It is difficult to reach this compromise, and this is the main reason behind the development of the Dynamic Flex, which can absorb the chop, without compromising the control and edging.")
(`Id`,`tmsCreate`,`userCreate`,`tmsEdit`,`userEdit`,`uid`,`gid`,`umod`,`gmod`,`omod`,`Titre`,`Icone`,`Ordre`,`Image`,`Texte`) VALUES ("41","1346919539","1","1383842547","103","1","0","7","7","7","Bamboo Sandwich Technologie","Home/103/Products/Technologie/Picto_bamboo_sandwich_tech_0.png","1","","All of our Surfs benefit from our Bamboo Sandwich Technology construction. Every layer of bamboo is reinforced with two layers of fiberglass. This allows the sandwich technology to emphasize the characteristics of the bamboo. The final result is a light structure that is super strong and extremely reliable.")
(`Id`,`tmsCreate`,`userCreate`,`tmsEdit`,`userEdit`,`uid`,`gid`,`umod`,`gmod`,`omod`,`Titre`,`Icone`,`Ordre`,`Image`,`Texte`) VALUES ("43","1346921420","1","1383842547","103","1","0","7","7","7","Double bamboo","Home/103/Products/Technologie/Picto_SURF_double_bamboo_deck_0.png","2","","The top deck of the board is lined with a double layer of bamboo.  The bamboo will ensure that the deck will be solid and resistant to pressure dings.")
(`Id`,`tmsCreate`,`userCreate`,`tmsEdit`,`userEdit`,`uid`,`gid`,`umod`,`gmod`,`omod`,`Titre`,`Icone`,`Ordre`,`Image`,`Texte`) VALUES ("44","1346921481","1","1383842547","103","1","0","7","7","7","Full bamboo","Home/103/Products/Technologie/Picto_SURF_full_bamboo_0.png","3","Home/103/Products/Technologie/SURF_BAMBOOST_FB_en_0.png","The full bamboo construction has been developed to strengthen the hull and the deck o the board.  An optimal ratio weight/ resistance has been achieved!")
(`Id`,`tmsCreate`,`userCreate`,`tmsEdit`,`userEdit`,`uid`,`gid`,`umod`,`gmod`,`omod`,`Titre`,`Icone`,`Ordre`,`Image`,`Texte`) VALUES ("11","1291822430","1","1383749616","101","1","0","7","7","7","Force Frame","Home/101/Products/Technologie/force_frame_0.png","2","","")
(`Id`,`tmsCreate`,`userCreate`,`tmsEdit`,`userEdit`,`uid`,`gid`,`umod`,`gmod`,`omod`,`Titre`,`Icone`,`Ordre`,`Image`,`Texte`) VALUES ("12","1291822448","1","1383749616","101","1","0","7","7","7","DELTA","Home/101/Products/Technologie/delta_c_shape_0.png","1","","")
(`Id`,`tmsCreate`,`userCreate`,`tmsEdit`,`userEdit`,`uid`,`gid`,`umod`,`gmod`,`omod`,`Titre`,`Icone`,`Ordre`,`Image`,`Texte`) VALUES ("71","1383748256","101","1383749616","101","101","109","7","7","7","","Home/101/Products/Technologie/auto_relaunch_1.png","0","","")
(`Id`,`tmsCreate`,`userCreate`,`tmsEdit`,`userEdit`,`uid`,`gid`,`umod`,`gmod`,`omod`,`Titre`,`Icone`,`Ordre`,`Image`,`Texte`) VALUES ("70","1383748009","101","1383749616","101","101","109","7","7","7","","Home/101/Products/Technologie/EVO_1.png","0","","")
(`Id`,`tmsCreate`,`userCreate`,`tmsEdit`,`userEdit`,`uid`,`gid`,`umod`,`gmod`,`omod`,`Titre`,`Icone`,`Ordre`,`Image`,`Texte`) VALUES ("10","1291822406","1","1383749616","101","1","0","7","7","7","Fusion Struts","Home/101/Products/Technologie/fusion_struts_0.png","3","","")
(`Id`,`tmsCreate`,`userCreate`,`tmsEdit`,`userEdit`,`uid`,`gid`,`umod`,`gmod`,`omod`,`Titre`,`Icone`,`Ordre`,`Image`,`Texte`) VALUES ("66","1378826155","1","1383842238","103","1","0","7","7","7","Twist Control","Home/103/Products/Technologie/Picto_X_twist_control_0.png","1","","The Twist Control, or Twist Carbon Control on certain models, allows to manage the board&acirc;Äôs twist and transversal reactivity. Depending on the model, this cross-shaped structure is either an add-on or cnc-machined directly into the mass of the wood core. Using it is also a guarantee of a better control whatever the water conditions. TC &amp; TCC can also optimize the ratio weight/rigidity and weight/reactivity")
(`Id`,`tmsCreate`,`userCreate`,`tmsEdit`,`userEdit`,`uid`,`gid`,`umod`,`gmod`,`omod`,`Titre`,`Icone`,`Ordre`,`Image`,`Texte`) VALUES ("67","1378826196","1","1383842267","103","1","0","7","7","7","V Double Concave","Home/103/Products/Technologie/Picto_double_concave_0.png","2","","The V shape you can find on the TRAX is variable along the board. Smaller in the center, the V double concave is at its max under the feet, and eventually disappear at the tips.")
(`Id`,`tmsCreate`,`userCreate`,`tmsEdit`,`userEdit`,`uid`,`gid`,`umod`,`gmod`,`omod`,`Titre`,`Icone`,`Ordre`,`Image`,`Texte`) VALUES ("69","1378827241","1","1383842396","103","1","0","7","7","7","Camel Drive Deck","Home/103/Products/Technologie/Picto_Camel_deck_0.png","4","","How many surfers have broken boards and wished they could replace it with a new one and get the same sensations they are used too?
Mitu once asked me: &acirc;ÄúRaph, can you try this board and make me the same one; it feels really good under my feet&acirc;Äù
I went out and tested this strapless board and was astonished by the control and sensations that the board gave me.  After a few runs, I started analyzing what was giving me this sensation of control.  I realized that my front foot was nestled in a heel dent and that my arch was fully supported on the rounded deck.  I could see that Mitu had spent so many hours on the board, that it had taken the shape of his foot.
I then understood that I needed to make a board with the top deck pre-shaped to get this sensation on a new board.
With its unique design, the Camel Drive Deck will offer multiple advantages:  It will lower and stabilize the heel of the surfer and lock its arch on a rounded center line.  It will improve stability, maneuverability and increase the rider&acirc;Äôs board control in any conditions.")
(`Id`,`tmsCreate`,`userCreate`,`tmsEdit`,`userEdit`,`uid`,`gid`,`umod`,`gmod`,`omod`,`Titre`,`Icone`,`Ordre`,`Image`,`Texte`) VALUES ("21","1346841282","1","1383842317","103","1","0","7","7","7","ABS Inverted Rail","Home/103/Products/Technologie/Picto_ABS_inverted_rail_0.png","2","","We sought to gain support and a more progressive and constant contact in the water. Starting with a surfing rail type, we have only kept the bottom part and the result is a reversed rail profile. Its entry into the water is more gradual and the board feedback is softer.")
(`Id`,`tmsCreate`,`userCreate`,`tmsEdit`,`userEdit`,`uid`,`gid`,`umod`,`gmod`,`omod`,`Titre`,`Icone`,`Ordre`,`Image`,`Texte`) VALUES ("68","1378826522","1","1383842267","103","1","0","7","7","7","Dual Core technology","Home/1/Products/Technologie/Dual_Core_64_0.png","3","","")
(`Id`,`tmsCreate`,`userCreate`,`tmsEdit`,`userEdit`,`uid`,`gid`,`umod`,`gmod`,`omod`,`Titre`,`Icone`,`Ordre`,`Image`,`Texte`) VALUES ("59","1348144541","1","1383842317","103","1","0","7","7","7","Wood Core","Home/103/Products/Technologie/Picto_wood_core_0.png","6","","The wood forms the heart of your board and gives it most of its mechanical properties: strength, flex and resilience (ability to return to its original shape). Each year, in order to master these properties, we seek to optimize its distribution, particularly in terms of thickness.")
(`Id`,`tmsCreate`,`userCreate`,`tmsEdit`,`userEdit`,`uid`,`gid`,`umod`,`gmod`,`omod`,`Titre`,`Icone`,`Ordre`,`Image`,`Texte`) VALUES ("60","1348144608","1","1383842317","103","1","0","7","7","7","Unibox","Home/103/Products/Technologie/Picto_unibox_0.png","7","Home/103/Products/Technologie/Focus_FINS_2013_40_a_0.png","The patented UNIBOX system and RESPONSE fins have a radical effect : the asymmetrical profile improves the  general ride and early planing. However, it is the flex of the RESPONSE fins that gives amazing rail-grip as well as pop and forgiveness on heavy freestyle landings.")
(`Id`,`tmsCreate`,`userCreate`,`tmsEdit`,`userEdit`,`uid`,`gid`,`umod`,`gmod`,`omod`,`Titre`,`Icone`,`Ordre`,`Image`,`Texte`) VALUES ("61","1378730795","1","1383833267","103","1","0","7","7","7","TECHNOFORCE&acirc;Ñ&cent; FABRIC","Home/103/Products/Technologie/Picto_KITE_TECHNOFORCE_by_TEIJIN_0.png","4","","TECHNOFORCE&acirc;Ñ&cent; is a high density fabric with a tear stopping structure using thin and high tension yarn.")
(`Id`,`tmsCreate`,`userCreate`,`tmsEdit`,`userEdit`,`uid`,`gid`,`umod`,`gmod`,`omod`,`Titre`,`Icone`,`Ordre`,`Image`,`Texte`) VALUES ("62","1378823834","1","1383842165","103","1","0","7","7","7","Helical Rail Design","Home/103/Products/Technologie/Picto_Helical_rail_design_0.png","1","","")
(`Id`,`tmsCreate`,`userCreate`,`tmsEdit`,`userEdit`,`uid`,`gid`,`umod`,`gmod`,`omod`,`Titre`,`Icone`,`Ordre`,`Image`,`Texte`) VALUES ("63","1378823941","1","1383842042","103","1","0","7","7","7","Carbon Series","Home/103/Products/Technologie/Picto_Carbon_series_0.png","2","","")
(`Id`,`tmsCreate`,`userCreate`,`tmsEdit`,`userEdit`,`uid`,`gid`,`umod`,`gmod`,`omod`,`Titre`,`Icone`,`Ordre`,`Image`,`Texte`) VALUES ("64","1378824022","1","1383842267","103","1","0","7","7","7","Hybrid Cap Rail ABS","Home/103/Products/Technologie/Picto_Hybrid_Cap_rail_ABS_0.png","1","Home/101/Products/Technologie/bandit_0.jpg","Hybrid Cap Rail is a construction process which cleverly combines the sleek lines and perfect grip of a cap construction rail with the toughness and durability of an ABS rail. As on a cap construction, the deck comes down towards the rail but finishes on a rounded ABS sidewall providing a shape similar to a surf style rail.")
(`Id`,`tmsCreate`,`userCreate`,`tmsEdit`,`userEdit`,`uid`,`gid`,`umod`,`gmod`,`omod`,`Titre`,`Icone`,`Ordre`,`Image`,`Texte`) VALUES ("65","1378824370","1","1383842165","103","1","0","7","7","7","Concave Step Design","Home/103/Products/Technologie/Picto_Concave_steps_design_0.png","4","Home/101/Products/Technologie/techno_constr_0.jpg","The combination of a bottom concave and a channel which tightens the central part, allows to go planning in an instant, with strong upwind potential. The concave absorbs the chop and improves its grip on the water. The channel enhances the flow of the water and relieves the pressure on the back foot, providing incomparable comfort.")
