<?php
/**
 * SubaccountRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Isendpro
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API iSendPro
 *
 * [1] Liste des fonctionnalités : - envoi de SMS à un ou plusieurs destinataires, - lookup HLR, - récupération des récapitulatifs de campagne, - gestion des répertoires, - ajout en liste noire. - comptage du nombre de caractères des SMS  [2] Pour utiliser cette API vous devez: - Créer un compte iSendPro sur https://isendpro.com/ - Créditer votre compte      - Remarque: obtention d'un crédit de test possible sous conditions - Noter votre clé de compte (keyid)   - Elle vous sera indispensable à l'utilisation de l'API   - Vous pouvez la trouver dans le rubrique mon \"compte\", sous-rubrique \"mon API\" - Configurer le contrôle IP   - Le contrôle IP est configurable dans le rubrique mon \"compte\", sous-rubrique \"mon API\"   - Il s'agit d'un système de liste blanche, vous devez entrer les IP utilisées pour appeler l'API   - Vous pouvez également désactiver totalement le contrôle IP
 *
 * OpenAPI spec version: 1.1.1
 * Contact: support@isendpro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Isendpro\Model;

use \ArrayAccess;

/**
 * SubaccountRequest Class Doc Comment
 *
 * @category    Class
 * @package     Isendpro
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SubaccountRequest implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'SubaccountRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'keyid' => 'string',
        'sub_account_edit' => 'string',
        'sub_account_key_id' => 'string',
        'sub_account_add_credit' => 'string',
        'sub_account_restriction_stop' => 'string',
        'sub_account_restriction_time' => 'string',
        'sub_account_price' => 'string',
        'sub_account_country_code' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'keyid' => null,
        'sub_account_edit' => null,
        'sub_account_key_id' => null,
        'sub_account_add_credit' => null,
        'sub_account_restriction_stop' => null,
        'sub_account_restriction_time' => null,
        'sub_account_price' => null,
        'sub_account_country_code' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'keyid' => 'keyid',
        'sub_account_edit' => 'subAccountEdit',
        'sub_account_key_id' => 'subAccountKeyId',
        'sub_account_add_credit' => 'subAccountAddCredit',
        'sub_account_restriction_stop' => 'subAccountRestrictionStop',
        'sub_account_restriction_time' => 'subAccountRestrictionTime',
        'sub_account_price' => 'subAccountPrice',
        'sub_account_country_code' => 'subAccountCountryCode'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'keyid' => 'setKeyid',
        'sub_account_edit' => 'setSubAccountEdit',
        'sub_account_key_id' => 'setSubAccountKeyId',
        'sub_account_add_credit' => 'setSubAccountAddCredit',
        'sub_account_restriction_stop' => 'setSubAccountRestrictionStop',
        'sub_account_restriction_time' => 'setSubAccountRestrictionTime',
        'sub_account_price' => 'setSubAccountPrice',
        'sub_account_country_code' => 'setSubAccountCountryCode'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'keyid' => 'getKeyid',
        'sub_account_edit' => 'getSubAccountEdit',
        'sub_account_key_id' => 'getSubAccountKeyId',
        'sub_account_add_credit' => 'getSubAccountAddCredit',
        'sub_account_restriction_stop' => 'getSubAccountRestrictionStop',
        'sub_account_restriction_time' => 'getSubAccountRestrictionTime',
        'sub_account_price' => 'getSubAccountPrice',
        'sub_account_country_code' => 'getSubAccountCountryCode'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    const SUB_ACCOUNT_EDIT_SET_PRICE = 'setPrice';
    const SUB_ACCOUNT_EDIT_ADD_CREDIT = 'addCredit';
    const SUB_ACCOUNT_EDIT_SET_RESTRICTION = 'setRestriction';
    const SUB_ACCOUNT_RESTRICTION_STOP__0 = '0';
    const SUB_ACCOUNT_RESTRICTION_STOP__1 = '1';
    const SUB_ACCOUNT_RESTRICTION_TIME__0 = '0';
    const SUB_ACCOUNT_RESTRICTION_TIME__1 = '1';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getSubAccountEditAllowableValues()
    {
        return [
            self::SUB_ACCOUNT_EDIT_SET_PRICE,
            self::SUB_ACCOUNT_EDIT_ADD_CREDIT,
            self::SUB_ACCOUNT_EDIT_SET_RESTRICTION,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getSubAccountRestrictionStopAllowableValues()
    {
        return [
            self::SUB_ACCOUNT_RESTRICTION_STOP__0,
            self::SUB_ACCOUNT_RESTRICTION_STOP__1,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getSubAccountRestrictionTimeAllowableValues()
    {
        return [
            self::SUB_ACCOUNT_RESTRICTION_TIME__0,
            self::SUB_ACCOUNT_RESTRICTION_TIME__1,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['keyid'] = isset($data['keyid']) ? $data['keyid'] : null;
        $this->container['sub_account_edit'] = isset($data['sub_account_edit']) ? $data['sub_account_edit'] : null;
        $this->container['sub_account_key_id'] = isset($data['sub_account_key_id']) ? $data['sub_account_key_id'] : null;
        $this->container['sub_account_add_credit'] = isset($data['sub_account_add_credit']) ? $data['sub_account_add_credit'] : null;
        $this->container['sub_account_restriction_stop'] = isset($data['sub_account_restriction_stop']) ? $data['sub_account_restriction_stop'] : null;
        $this->container['sub_account_restriction_time'] = isset($data['sub_account_restriction_time']) ? $data['sub_account_restriction_time'] : null;
        $this->container['sub_account_price'] = isset($data['sub_account_price']) ? $data['sub_account_price'] : null;
        $this->container['sub_account_country_code'] = isset($data['sub_account_country_code']) ? $data['sub_account_country_code'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['keyid'] === null) {
            $invalid_properties[] = "'keyid' can't be null";
        }
        if ($this->container['sub_account_edit'] === null) {
            $invalid_properties[] = "'sub_account_edit' can't be null";
        }
        $allowed_values = $this->getSubAccountEditAllowableValues();
        if (!in_array($this->container['sub_account_edit'], $allowed_values)) {
            $invalid_properties[] = sprintf(
                "invalid value for 'sub_account_edit', must be one of '%s'",
                implode("', '", $allowed_values)
            );
        }

        $allowed_values = $this->getSubAccountRestrictionStopAllowableValues();
        if (!in_array($this->container['sub_account_restriction_stop'], $allowed_values)) {
            $invalid_properties[] = sprintf(
                "invalid value for 'sub_account_restriction_stop', must be one of '%s'",
                implode("', '", $allowed_values)
            );
        }

        $allowed_values = $this->getSubAccountRestrictionTimeAllowableValues();
        if (!in_array($this->container['sub_account_restriction_time'], $allowed_values)) {
            $invalid_properties[] = sprintf(
                "invalid value for 'sub_account_restriction_time', must be one of '%s'",
                implode("', '", $allowed_values)
            );
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['keyid'] === null) {
            return false;
        }
        if ($this->container['sub_account_edit'] === null) {
            return false;
        }
        $allowed_values = $this->getSubAccountEditAllowableValues();
        if (!in_array($this->container['sub_account_edit'], $allowed_values)) {
            return false;
        }
        $allowed_values = $this->getSubAccountRestrictionStopAllowableValues();
        if (!in_array($this->container['sub_account_restriction_stop'], $allowed_values)) {
            return false;
        }
        $allowed_values = $this->getSubAccountRestrictionTimeAllowableValues();
        if (!in_array($this->container['sub_account_restriction_time'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets keyid
     * @return string
     */
    public function getKeyid()
    {
        return $this->container['keyid'];
    }

    /**
     * Sets keyid
     * @param string $keyid Clé API
     * @return $this
     */
    public function setKeyid($keyid)
    {
        $this->container['keyid'] = $keyid;

        return $this;
    }

    /**
     * Gets sub_account_edit
     * @return string
     */
    public function getSubAccountEdit()
    {
        return $this->container['sub_account_edit'];
    }

    /**
     * Sets sub_account_edit
     * @param string $sub_account_edit action à réaliser soit setPrice pour définir un prix ou addCredit pour ajouter du credit ou setRestriction modifier la restriction stop /
     * @return $this
     */
    public function setSubAccountEdit($sub_account_edit)
    {
        $allowed_values = $this->getSubAccountEditAllowableValues();
        if (!in_array($sub_account_edit, $allowed_values)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'sub_account_edit', must be one of '%s'",
                    implode("', '", $allowed_values)
                )
            );
        }
        $this->container['sub_account_edit'] = $sub_account_edit;

        return $this;
    }

    /**
     * Gets sub_account_key_id
     * @return string
     */
    public function getSubAccountKeyId()
    {
        return $this->container['sub_account_key_id'];
    }

    /**
     * Sets sub_account_key_id
     * @param string $sub_account_key_id keyid du sous-compte
     * @return $this
     */
    public function setSubAccountKeyId($sub_account_key_id)
    {
        $this->container['sub_account_key_id'] = $sub_account_key_id;

        return $this;
    }

    /**
     * Gets sub_account_add_credit
     * @return string
     */
    public function getSubAccountAddCredit()
    {
        return $this->container['sub_account_add_credit'];
    }

    /**
     * Sets sub_account_add_credit
     * @param string $sub_account_add_credit montant du crédit à ajouter
     * @return $this
     */
    public function setSubAccountAddCredit($sub_account_add_credit)
    {
        $this->container['sub_account_add_credit'] = $sub_account_add_credit;

        return $this;
    }

    /**
     * Gets sub_account_restriction_stop
     * @return string
     */
    public function getSubAccountRestrictionStop()
    {
        return $this->container['sub_account_restriction_stop'];
    }

    /**
     * Sets sub_account_restriction_stop
     * @param string $sub_account_restriction_stop
     * @return $this
     */
    public function setSubAccountRestrictionStop($sub_account_restriction_stop)
    {
        $allowed_values = $this->getSubAccountRestrictionStopAllowableValues();
        if (!is_null($sub_account_restriction_stop) && !in_array($sub_account_restriction_stop, $allowed_values)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'sub_account_restriction_stop', must be one of '%s'",
                    implode("', '", $allowed_values)
                )
            );
        }
        $this->container['sub_account_restriction_stop'] = $sub_account_restriction_stop;

        return $this;
    }

    /**
     * Gets sub_account_restriction_time
     * @return string
     */
    public function getSubAccountRestrictionTime()
    {
        return $this->container['sub_account_restriction_time'];
    }

    /**
     * Sets sub_account_restriction_time
     * @param string $sub_account_restriction_time
     * @return $this
     */
    public function setSubAccountRestrictionTime($sub_account_restriction_time)
    {
        $allowed_values = $this->getSubAccountRestrictionTimeAllowableValues();
        if (!is_null($sub_account_restriction_time) && !in_array($sub_account_restriction_time, $allowed_values)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'sub_account_restriction_time', must be one of '%s'",
                    implode("', '", $allowed_values)
                )
            );
        }
        $this->container['sub_account_restriction_time'] = $sub_account_restriction_time;

        return $this;
    }

    /**
     * Gets sub_account_price
     * @return string
     */
    public function getSubAccountPrice()
    {
        return $this->container['sub_account_price'];
    }

    /**
     * Sets sub_account_price
     * @param string $sub_account_price
     * @return $this
     */
    public function setSubAccountPrice($sub_account_price)
    {
        $this->container['sub_account_price'] = $sub_account_price;

        return $this;
    }

    /**
     * Gets sub_account_country_code
     * @return string
     */
    public function getSubAccountCountryCode()
    {
        return $this->container['sub_account_country_code'];
    }

    /**
     * Sets sub_account_country_code
     * @param string $sub_account_country_code
     * @return $this
     */
    public function setSubAccountCountryCode($sub_account_country_code)
    {
        $this->container['sub_account_country_code'] = $sub_account_country_code;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Isendpro\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Isendpro\ObjectSerializer::sanitizeForSerialization($this));
    }
}


