<?php
/**
 * REPERTOIREmodifrequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Isendpro
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API iSendPro
 *
 * [1] Liste des fonctionnalités : - envoi de SMS à un ou plusieurs destinataires, - lookup HLR, - récupération des récapitulatifs de campagne, - gestion des répertoires, - ajout en liste noire. - comptage du nombre de caractères des SMS  [2] Pour utiliser cette API vous devez: - Créer un compte iSendPro sur https://isendpro.com/ - Créditer votre compte      - Remarque: obtention d'un crédit de test possible sous conditions - Noter votre clé de compte (keyid)   - Elle vous sera indispensable à l'utilisation de l'API   - Vous pouvez la trouver dans le rubrique mon \"compte\", sous-rubrique \"mon API\" - Configurer le contrôle IP   - Le contrôle IP est configurable dans le rubrique mon \"compte\", sous-rubrique \"mon API\"   - Il s'agit d'un système de liste blanche, vous devez entrer les IP utilisées pour appeler l'API   - Vous pouvez également désactiver totalement le contrôle IP
 *
 * OpenAPI spec version: 1.1.1
 * Contact: support@isendpro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Isendpro;

/**
 * REPERTOIREmodifrequestTest Class Doc Comment
 *
 * @category    Class */
// * @description REPERTOIREmodifrequest
/**
 * @package     Isendpro
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class REPERTOIREmodifrequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "REPERTOIREmodifrequest"
     */
    public function testREPERTOIREmodifrequest()
    {
    }

    /**
     * Test attribute "keyid"
     */
    public function testPropertyKeyid()
    {
    }

    /**
     * Test attribute "repertoire_edit"
     */
    public function testPropertyRepertoireEdit()
    {
    }

    /**
     * Test attribute "repertoire_id"
     */
    public function testPropertyRepertoireId()
    {
    }

    /**
     * Test attribute "num"
     */
    public function testPropertyNum()
    {
    }

    /**
     * Test attribute "champ1"
     */
    public function testPropertyChamp1()
    {
    }

    /**
     * Test attribute "champ2"
     */
    public function testPropertyChamp2()
    {
    }

    /**
     * Test attribute "champ3"
     */
    public function testPropertyChamp3()
    {
    }

    /**
     * Test attribute "champ4"
     */
    public function testPropertyChamp4()
    {
    }

    /**
     * Test attribute "champ5"
     */
    public function testPropertyChamp5()
    {
    }

    /**
     * Test attribute "champ6"
     */
    public function testPropertyChamp6()
    {
    }

    /**
     * Test attribute "champ7"
     */
    public function testPropertyChamp7()
    {
    }

    /**
     * Test attribute "champ8"
     */
    public function testPropertyChamp8()
    {
    }

    /**
     * Test attribute "champ9"
     */
    public function testPropertyChamp9()
    {
    }

    /**
     * Test attribute "champ10"
     */
    public function testPropertyChamp10()
    {
    }

    /**
     * Test attribute "champ11"
     */
    public function testPropertyChamp11()
    {
    }

    /**
     * Test attribute "champ12"
     */
    public function testPropertyChamp12()
    {
    }

    /**
     * Test attribute "champ13"
     */
    public function testPropertyChamp13()
    {
    }

    /**
     * Test attribute "champ14"
     */
    public function testPropertyChamp14()
    {
    }

    /**
     * Test attribute "champ15"
     */
    public function testPropertyChamp15()
    {
    }

    /**
     * Test attribute "champ16"
     */
    public function testPropertyChamp16()
    {
    }

    /**
     * Test attribute "champ17"
     */
    public function testPropertyChamp17()
    {
    }

    /**
     * Test attribute "champ18"
     */
    public function testPropertyChamp18()
    {
    }

    /**
     * Test attribute "champ19"
     */
    public function testPropertyChamp19()
    {
    }

    /**
     * Test attribute "champ20"
     */
    public function testPropertyChamp20()
    {
    }

    /**
     * Test attribute "champ21"
     */
    public function testPropertyChamp21()
    {
    }

    /**
     * Test attribute "champ22"
     */
    public function testPropertyChamp22()
    {
    }

    /**
     * Test attribute "champ23"
     */
    public function testPropertyChamp23()
    {
    }

    /**
     * Test attribute "champ24"
     */
    public function testPropertyChamp24()
    {
    }

    /**
     * Test attribute "champ25"
     */
    public function testPropertyChamp25()
    {
    }

    /**
     * Test attribute "champ26"
     */
    public function testPropertyChamp26()
    {
    }

    /**
     * Test attribute "champ27"
     */
    public function testPropertyChamp27()
    {
    }
}
