<?php
/**
 * SmsUniqueRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Isendpro
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API iSendPro
 *
 * [1] Liste des fonctionnalités : - envoi de SMS à un ou plusieurs destinataires, - lookup HLR, - récupération des récapitulatifs de campagne, - gestion des répertoires, - ajout en liste noire. - comptage du nombre de caractères des SMS  [2] Pour utiliser cette API vous devez: - Créer un compte iSendPro sur https://isendpro.com/ - Créditer votre compte      - Remarque: obtention d'un crédit de test possible sous conditions - Noter votre clé de compte (keyid)   - Elle vous sera indispensable à l'utilisation de l'API   - Vous pouvez la trouver dans le rubrique mon \"compte\", sous-rubrique \"mon API\" - Configurer le contrôle IP   - Le contrôle IP est configurable dans le rubrique mon \"compte\", sous-rubrique \"mon API\"   - Il s'agit d'un système de liste blanche, vous devez entrer les IP utilisées pour appeler l'API   - Vous pouvez également désactiver totalement le contrôle IP
 *
 * OpenAPI spec version: 1.1.1
 * Contact: support@isendpro.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Isendpro;

/**
 * SmsUniqueRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description SmsUniqueRequest
/**
 * @package     Isendpro
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SmsUniqueRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SmsUniqueRequest"
     */
    public function testSmsUniqueRequest()
    {
    }

    /**
     * Test attribute "keyid"
     */
    public function testPropertyKeyid()
    {
    }

    /**
     * Test attribute "gmt_zone"
     */
    public function testPropertyGmtZone()
    {
    }

    /**
     * Test attribute "date_envoi"
     */
    public function testPropertyDateEnvoi()
    {
    }

    /**
     * Test attribute "sms"
     */
    public function testPropertySms()
    {
    }

    /**
     * Test attribute "num"
     */
    public function testPropertyNum()
    {
    }

    /**
     * Test attribute "emetteur"
     */
    public function testPropertyEmetteur()
    {
    }

    /**
     * Test attribute "tracker"
     */
    public function testPropertyTracker()
    {
    }

    /**
     * Test attribute "smslong"
     */
    public function testPropertySmslong()
    {
    }

    /**
     * Test attribute "nostop"
     */
    public function testPropertyNostop()
    {
    }

    /**
     * Test attribute "num_azur"
     */
    public function testPropertyNumAzur()
    {
    }

    /**
     * Test attribute "ucs2"
     */
    public function testPropertyUcs2()
    {
    }
}
